<a href="https://colab.research.google.com/github/raphha/PLN/blob/main/classSPAMcomRN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout
from google.colab import files

In [ ]:
files.upload()


In [5]:
spam = pd.read_csv("spam.csv")

In [6]:
spam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(spam['Category'])
print(y)

[0 0 1 ... 0 0 0]


In [12]:
mensagens = spam['Message'].values
x_train, x_test, y_train, y_test = train_test_split(mensagens, y, test_size=0.3)

In [9]:
print(x_train)

['I dont have that much image in class.' 'U GOIN OUT 2NITE?'
 '3. You have received your mobile content. Enjoy' ...
 "Hasn't that been the pattern recently crap weekends?"
 "No sir. That's why i had an 8-hr trip on the bus last week. Have another audition next wednesday but i think i might drive this time."
 "I thought i'd get him a watch, just cos thats the kind of thing u get4an18th. And he loves so much!"]


In [13]:
vetorizador = CountVectorizer()
vetorizador.fit(x_train)
x_train = vetorizador.transform(x_train)
x_test = vetorizador.transform(x_test)
print(x_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
import numpy as np
np.set_printoptions(threshold =np.inf)

In [ ]:
x_train.toarray()[0]

In [18]:
print(x_train.shape[1])

7285


In [19]:
modelo = Sequential()
#10 é o número de neurônios (aleatório). Input dim é o número de atributos, neste caso do vetor
modelo.add(Dense(units=10, activation="relu", input_dim=x_train.shape[1]))
modelo.add(Dropout(0.1)) #diminui o overfiting
#somente na primeira camada é necessário definir o número de entradas
modelo.add(Dense(units=8, activation="relu"))
modelo.add(Dropout(0.1))
#na última camada deve ser colocado o número de classes
modelo.add(Dense(units=1, activation="sigmoid"))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │          72,860 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 10)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 8)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 72,957 (284.99 KB)

 Trainable params: 72,957 (284.99 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
modelo.fit(x_train, y_train, epochs=20, batch_size=10, verbose=True, validation_data=(x_test, y_test))
#o epochs deve ser maior (500), aqui esta pequeno por ser estudo

Epoch 1/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8794 - loss: 0.1315 - val_accuracy: 0.9731 - val_loss: 0.0323
Epoch 2/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9867 - loss: 0.0180 - val_accuracy: 0.9815 - val_loss: 0.0171
Epoch 3/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9959 - loss: 0.0050 - val_accuracy: 0.9844 - val_loss: 0.0145
Epoch 4/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9979 - loss: 0.0024 - val_accuracy: 0.9850 - val_loss: 0.0143
Epoch 5/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9978 - loss: 0.0025 - val_accuracy: 0.9833 - val_loss: 0.0150
Epoch 6/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9995 - loss: 0.0017 - val_accuracy: 0.9839 - val_loss: 0.0153
Epoch 7/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9984 - loss: 0.0019 - val_accuracy: 0.9833 - val_loss: 0.0159
Epoch 8/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9995 - loss: 0.0010 - val_accuracy: 0.

In [26]:
loss, accuracy = modelo.evaluate(x_test, y_test)
print("loss:", loss)
print("Acurácia:", accuracy)

53/53 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9785 - loss: 0.0204
loss: 0.019439077004790306
Acurácia: 0.9784688949584961


In [ ]:
nova_previsao = modelo.predict(x_test)
print(nova_previsao)

In [ ]:
prev = (nova_previsao>0.5)
print(prev)

In [29]:
cm = confusion_matrix(y_test, prev)
print(cm)

[[1427    4]
 [  32  209]]
